import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Space Club OAU",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/logo-black.webp" },
      new URL("/logo-black.webp", "https://spaceclub-oau.vercel.app"),
      { url: "/logo-white.webp", media: "(prefers-color-scheme: dark)" },
    ],
    shortcut: ["/logo-black.webp"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/logo-white.webp' />
      </head>
      <body className='max-w-screen font-manrope md:text-lg'>{children}</body>
    </html>
  );
}

